#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if [ -d /etc/steamp ]; then
            rm -rf /etc/steamp
        fi
        
        if [ -d /etc/systemd/system/steamp.service ]; then
            rm -rf /etc/systemd/system/steamp.service
        fi
	systemctl daemon-reload || true
        ;;
esac

exit 0
