#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -f /etc/systemd/system/steamp.service ]; then
            systemctl stop steamp
        fi
        ;;
esac

# Exit with status 0
exit 0
